version: '3.8'
services: 
  db:
    image: postgres:11  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: mydatabase 
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 
    networks:
      - app-network
  web: 
    build: .
    ports:  
      - "5000:5000"
    depends_on:    
      - db
    environment:   
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    networks: 
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
